"""contact table

Revision ID: 018ffda57b28
Revises: f779e134afb0
Create Date: 2019-04-20 16:54:06.465460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '018ffda57b28'
down_revision = 'f779e134afb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.String(length=400), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('comments', sa.Column('email', sa.String(length=50), nullable=True))
    op.add_column('comments', sa.Column('name', sa.String(length=20), nullable=True))
    op.drop_column('comments', 'user_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_name', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('comments', 'name')
    op.drop_column('comments', 'email')
    op.drop_table('contact')
    # ### end Alembic commands ###
