"""fields nullable is false

Revision ID: b5e31368b243
Revises: b6c69fcd610e
Create Date: 2019-04-13 22:28:13.571626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5e31368b243'
down_revision = 'b6c69fcd610e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'create_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('post', 'heading',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('post', 'post',
               existing_type=mysql.VARCHAR(length=2000),
               nullable=False)
    op.alter_column('post', 'update_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('role', 'default',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('role', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('tag', 'create_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('tag', 'name',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('tag', 'update_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('tagged', 'purchase_date')
    op.alter_column('user', 'create_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'firstname',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('user', 'last_seen',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('user', 'lastname',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('user', 'password_hash',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password_hash',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('user', 'lastname',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('user', 'last_seen',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user', 'firstname',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'create_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.add_column('tagged', sa.Column('purchase_date', mysql.DATETIME(), nullable=False))
    op.alter_column('tag', 'update_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('tag', 'name',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('tag', 'create_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('role', 'name',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('role', 'default',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('post', 'update_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('post', 'post',
               existing_type=mysql.VARCHAR(length=2000),
               nullable=True)
    op.alter_column('post', 'heading',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('post', 'create_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
