"""post current added

Revision ID: c52e8eaeccc7
Revises: 4682ab94384d
Create Date: 2019-04-15 16:56:01.064664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c52e8eaeccc7'
down_revision = '4682ab94384d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('current', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_post_current'), 'post', ['current'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_current'), table_name='post')
    op.drop_column('post', 'current')
    # ### end Alembic commands ###
