from flask import render_template
from . import bp

# 404 - Not Found and 500 - Internal server error are errors generated by Flask
# So we give these errors a nice template
@bp.app_errorhandler(404)
def page_not_found(e):
    return render_template('errors/404.html'), 404

@bp.app_errorhandler(500)
def internal_server_error(e):
    return render_template('errors/500.html'), 500
